#perl makestockholomMSAsubmit.pl --input /exports/home/scondon/Desktop/pfam_alignments/CATM_sequences.csv --inputDir /exports/home/scondon/Desktop/pfam_alignments/ --output glycineCountSubmit.sh
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF06553.stk --protein O60238 --output glycineCountSubmit.sh --residue 202 204 208 --interface 0 3 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB037446.stk --protein Q6UW88 --output glycineCountSubmit.sh --residue 115 117 119 124 --interface 2 0 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB006356.stk --protein Q16706 --output glycineCountSubmit.sh --residue 11 29 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB011796.stk --protein O75829 --output glycineCountSubmit.sh --residue 43 50 57 60 67 --interface 0 1 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF02060.stk --protein Q8WWG9 --output glycineCountSubmit.sh --residue 33 47 52 56 --interface 0 0 3 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB004076.stk --protein Q6UWL2 --output glycineCountSubmit.sh --residue 727 729 731 --interface 3 0 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB003534.stk --protein P14784 --output glycineCountSubmit.sh --residue 245 250 253 256 --interface 0 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF02060.stk --protein P15382 --output glycineCountSubmit.sh --residue 52 55 60 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF08294.stk --protein Q9BVV7 --output glycineCountSubmit.sh --residue 105 117 122 123 --interface 0 0 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB012009.stk --protein Q9NUV7 --output glycineCountSubmit.sh --residue 69 71 73 77 --interface 2 0 3 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF14991.stk --protein Q16655 --output glycineCountSubmit.sh --residue 29 31 38 44 --interface 0 0 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF07225.stk --protein O95168 --output glycineCountSubmit.sh --residue 90 94 96 --interface 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB009732.stk --protein Q96PQ0 --output glycineCountSubmit.sh --residue 1076 1077 1078 1079 1090 1095 --interface 0 0 0 0 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF10161.stk --protein Q9H4I9 --output glycineCountSubmit.sh --residue 66 81 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF05283.stk --protein Q04900 --output glycineCountSubmit.sh --residue 168 169 175 --interface 3 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB001661.stk --protein Q9Y679 --output glycineCountSubmit.sh --residue 20 35 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB022042.stk --protein Q7L211 --output glycineCountSubmit.sh --residue 41 42 55 --interface 3 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB034031.stk --protein Q9NS00 --output glycineCountSubmit.sh --residue 15 19 32 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF13908.stk --protein Q6UWI4 --output glycineCountSubmit.sh --residue 109 122 132 --interface 0 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF13908.stk --protein Q8N114 --output glycineCountSubmit.sh --residue 105 107 113 --interface 0 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB113004.stk --protein A8MXV6 --output glycineCountSubmit.sh --residue 208 216 225 --interface 2 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF06553.stk --protein Q12983 --output glycineCountSubmit.sh --residue 178 180 184 --interface 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB007811.stk --protein P17342 --output glycineCountSubmit.sh --residue 486 490 494 496 --interface 2 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB035279.stk --protein O60243 --output glycineCountSubmit.sh --residue 24 37 39 --interface 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF04505.stk --protein Q9H7V2 --output glycineCountSubmit.sh --residue 183 197 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF04418.stk --protein Q5TGZ0 --output glycineCountSubmit.sh --residue 22 24 26 28 --interface 0 2 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01734.stk --protein Q9NP80 --output glycineCountSubmit.sh --residue 481 485 493 --interface 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB005508.stk --protein Q9UH62 --output glycineCountSubmit.sh --residue 8 13 17 19 30 --interface 0 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF05827.stk --protein Q15904 --output glycineCountSubmit.sh --residue 425 429 443 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB034583.stk --protein Q96TC7 --output glycineCountSubmit.sh --residue 13 15 19 23 25 --interface 0 2 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF10247.stk --protein P60602 --output glycineCountSubmit.sh --residue 22 26 30 34 38 46 --interface 1 2 3 1 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF03414.stk --protein P16442 --output glycineCountSubmit.sh --residue 33 35 45 50 --interface 0 0 3 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB008842.stk --protein Q5TGI0 --output glycineCountSubmit.sh --residue 71 72 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF14851.stk --protein Q9NVM1 --output glycineCountSubmit.sh --residue 29 35 39 --interface 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF08039.stk --protein P56378 --output glycineCountSubmit.sh --residue 27 29 32 --interface 3 0 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF15139.stk --protein Q5VTT2 --output glycineCountSubmit.sh --residue 123 130 135 137 --interface 1 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF12191.stk --protein Q9NP84 --output glycineCountSubmit.sh --residue 83 84 93 97 --interface 0 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB001938.stk --protein Q9Y661 --output glycineCountSubmit.sh --residue 54 55 57 --interface 3 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF00429.stk --protein B6SEH8 --output glycineCountSubmit.sh --residue 323 328 330 334 340 341 --interface 1 0 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF14752.stk --protein Q9P1Z9 --output glycineCountSubmit.sh --residue 47 49 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF10873.stk --protein Q96J86 --output glycineCountSubmit.sh --residue 60 65 69 75 79 --interface 0 0 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01102.stk --protein P02724 --output glycineCountSubmit.sh --residue 98 102 105 113 --interface 2 2 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF08038.stk --protein Q9P0U1 --output glycineCountSubmit.sh --residue 18 26 35 39 --interface 0 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF14986.stk --protein Q5T292 --output glycineCountSubmit.sh --residue 40 44 50 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF06916.stk --protein Q96ND0 --output glycineCountSubmit.sh --residue 134 146 150 159 --interface 0 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB000389.stk --protein Q96JX3 --output glycineCountSubmit.sh --residue 38 43 44 --interface 0 3 2 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB053299.stk --protein Q9P291 --output glycineCountSubmit.sh --residue 8 13 17 19 30 --interface 0 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF11628.stk --protein P20963 --output glycineCountSubmit.sh --residue 37 43 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB036396.stk --protein O43557 --output glycineCountSubmit.sh --residue 39 41 48 50 55 --interface 0 1 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB135923.stk --protein P32970 --output glycineCountSubmit.sh --residue 16 29 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB005508.stk --protein Q7L311 --output glycineCountSubmit.sh --residue 8 13 17 19 --interface 0 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01734.stk --protein Q9NST1 --output glycineCountSubmit.sh --residue 45 49 55 59 --interface 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB013908.stk --protein Q9UMD9 --output glycineCountSubmit.sh --residue 470 480 484 --interface 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF11803.stk --protein Q8NBZ7 --output glycineCountSubmit.sh --residue 23 35 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF05624.stk --protein Q86SU0 --output glycineCountSubmit.sh --residue 177 186 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB010758.stk --protein Q9NUB4 --output glycineCountSubmit.sh --residue 140 142 149 156 --interface 0 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB067151.stk --protein Q9NY28 --output glycineCountSubmit.sh --residue 14 31 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB020308.stk --protein O60512 --output glycineCountSubmit.sh --residue 17 29 30 --interface 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF08997.stk --protein O14957 --output glycineCountSubmit.sh --residue 25 28 31 --interface 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF00201.stk --protein Q6NUS8 --output glycineCountSubmit.sh --residue 494 498 504 --interface 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01102.stk --protein P02724 --output glycineCountSubmit.sh --residue 98 102 105 113 --interface 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF00201.stk --protein Q3SY77 --output glycineCountSubmit.sh --residue 494 498 504 --interface 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF00584.stk --protein P60059 --output glycineCountSubmit.sh --residue 43 48 51 --interface 0 3 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF15061.stk --protein Q8N5G0 --output glycineCountSubmit.sh --residue 113 114 120 --interface 3 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB028817.stk --protein Q96LC7 --output glycineCountSubmit.sh --residue 551 555 557 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF14962.stk --protein Q8TDB4 --output glycineCountSubmit.sh --residue 40 43 53 59 60 --interface 0 0 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB031580.stk --protein Q8IZ52 --output glycineCountSubmit.sh --residue 14 19 23 --interface 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB068724.stk --protein Q9UJ37 --output glycineCountSubmit.sh --residue 6 21 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01102.stk --protein P02724 --output glycineCountSubmit.sh --residue 98 102 105 113 --interface 1 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF09731.stk --protein Q16891 --output glycineCountSubmit.sh --residue 44 48 50 55 56 57 59 60 --interface 0 0 0 1 2 2 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB014359.stk --protein Q9NQG6 --output glycineCountSubmit.sh --residue 32 34 35 40 --interface 3 0 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB020620.stk --protein P20273 --output glycineCountSubmit.sh --residue 685 691 693 705 --interface 1 0 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB028004.stk --protein Q96EX1 --output glycineCountSubmit.sh --residue 25 28 37 --interface 2 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF14960.stk --protein Q96IX5 --output glycineCountSubmit.sh --residue 26 36 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF13908.stk --protein A0PJX4 --output glycineCountSubmit.sh --residue 103 113 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB022819.stk --protein Q12866 --output glycineCountSubmit.sh --residue 507 511 516 --interface 2 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB034935.stk --protein O00481 --output glycineCountSubmit.sh --residue 254 264 265 267 --interface 0 3 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB018352.stk --protein Q9Y442 --output glycineCountSubmit.sh --residue 35 37 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF09769.stk --protein Q9BUR5 --output glycineCountSubmit.sh --residue 109 115 118 121 124 130 --interface 0 1 2 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB035293.stk --protein Q3V5L5 --output glycineCountSubmit.sh --residue 28 30 42 43 --interface 0 0 3 2 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF05821.stk --protein O95169 --output glycineCountSubmit.sh --residue 135 147 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB002311.stk --protein O75309 --output glycineCountSubmit.sh --residue 788 792 798 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB004699.stk --protein Q9BYF1 --output glycineCountSubmit.sh --residue 747 751 756 764 --interface 3 1 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB022010.stk --protein Q8IZT8 --output glycineCountSubmit.sh --residue 17 22 32 --interface 0 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF05404.stk --protein P51571 --output glycineCountSubmit.sh --residue 144 157 --interface 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF00429.stk --protein Q9UQF0 --output glycineCountSubmit.sh --residue 453 465 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF15468.stk --protein Q8WWF3 --output glycineCountSubmit.sh --residue 36 39 --interface 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB002850.stk --protein Q15109 --output glycineCountSubmit.sh --residue 346 349 350 352 359 --interface 3 0 1 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB019676.stk --protein P27930 --output glycineCountSubmit.sh --residue 351 365 366 --interface 0 3 2 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB022830.stk --protein A6NL88 --output glycineCountSubmit.sh --residue 191 200 202 --interface 0 0 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF06990.stk --protein Q96RP7 --output glycineCountSubmit.sh --residue 19 23 29 36 37 --interface 0 0 1 3 2 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01034.stk --protein P18827 --output glycineCountSubmit.sh --residue 254 255 259 260 263 272 --interface 0 1 2 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF05808.stk --protein Q86YL7 --output glycineCountSubmit.sh --residue 133 137 143 146 --interface 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB003155.stk --protein Q9NSK7 --output glycineCountSubmit.sh --residue 53 54 57 58 61 65 66 69 70 73 --interface 0 1 0 1 2 3 2 1 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB117420.stk --protein A6H8M9 --output glycineCountSubmit.sh --residue 696 704 708 --interface 0 2 3 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB034297.stk --protein Q96C03 --output glycineCountSubmit.sh --residue 33 35 36 41 --interface 3 0 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF15096.stk --protein O95866 --output glycineCountSubmit.sh --residue 149 151 155 157 160 --interface 0 2 3 0 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF09794.stk --protein Q8NBF6 --output glycineCountSubmit.sh --residue 216 227 232 --interface 0 3 1 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF02238.stk --protein P24310 --output glycineCountSubmit.sh --residue 45 46 62 63 72 --interface 0 0 3 2 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF11980.stk --protein O60462 --output glycineCountSubmit.sh --residue 876 880 885 --interface 2 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF01299.stk --protein P11279 --output glycineCountSubmit.sh --residue 389 390 394 406 --interface 0 3 1 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB028674.stk --protein Q6ZWL3 --output glycineCountSubmit.sh --residue 17 26 --interface 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PF02285.stk --protein P10176 --output glycineCountSubmit.sh --residue 36 43 56 --interface 1 3 0 
perl /exports/home/scondon/mslib/trunk/myScripts/sgfc/stockholmMSA.pl --file /exports/home/scondon/Desktop/pfam_alignments//PB006304.stk --protein P02786 --output glycineCountSubmit.sh --residue 69 80 84 87 91 --interface 0 3 1 1 0 
